# Generated by Django 6.1 on 2026-08-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=models.CharField(max_length=9, verbose_name='Telefone'),
        ),
    ]
